language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "robert2411-github"

jdk:
  - oraclejdk8
script:
  - mvn clean cobertura:cobertura org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dmaven.test.failure.ignore=true

after_success:
    - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
